Backend/main_app/config/routes.rb
MainApp::Application.routes.draw do
  authenticated :user do
    root :to => 'home#index'
  end
  root :to => 'home#index'

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

  devise_for :users
  resources :users

end

Backend/main_app/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

Backend/main_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

Backend/main_app/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

Backend/main_app/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

Backend/main_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

Backend/main_app/app/helpers/application_helper.rb
module ApplicationHelper

# Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "WebProject"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
  
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

Backend/main_app/app/helpers/home_helper.rb
module HomeHelper
end

Backend/main_app/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

Backend/main_app/app/helpers/users_helper.rb
module UsersHelper
end

Backend/main_app/app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">

    <div class="container"> 

	    <div class="row" id="main-content">

		    <div class="span8">
			    <div id="slider" class="carousel slide">
				    <div class="carousel-inner">
					    <div class="item active">
						    <img src="http://placehold.it/850x500">
						    <div class="carousel-caption">
							    <h4>Headline for Image 1</h4>
							    <p>Description of image 1</p>
						    </div>
					    </div>
					    <div class="item">
						    <img src="http://placehold.it/850x500">
						    <div class="carousel-caption">
							    <h4>Headline for Image 2</h4>
							    <p>Description of image 2</p>
						    </div>
					    </div>
					    <div class="item">
						    <img src="http://placehold.it/850x500">
						    <div class="carousel-caption">
							    <h4>Headline for Image 3</h4>
							    <p>Description of image 3</p>
						    </div>
					    </div>
				    </div>
				    <a class="left carousel-control" href="#slider" data-slide="prev">&lsaquo;</a>
				    <a class="right carousel-control" href="#slider" data-slide="prev">&rsaquo;</a>
			    </div>
		    </div>
        
		    <div class="span4"> 
				<% if user_signed_in? %>
                  <li>
                    <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
				  </li>
				<% else %>
                  <li>
				    <%= render 'users/sign_in' %>
                  </li>
                <% end %>
			</div>

		    <footer class="row"></footer>
 
	    </div> <!end of container> 
    </div>

    <div id="register" class="modal hide fade" aria-labelledby="modalLabel" aria-hidden="true">

	    <div class="modal-header">
		    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="icon-remove"></i>
			    <h3 id=modamlabel">Register</h3>

	    </div>

	    <div class="modal-body">
		    <form>

			    <p class="label label-info">Required</p>

			    <div class="controls controls-group info">
				    <input type="text" class="span4" placeholder="username" id="inputinfo">
				    <input type="text" class="span4" placeholder="email" id="inputinfo">
				    <input type="text" class="span4" placeholder="password" id="inputinfo">
			    </div>

			    <p class="help-block">I will be posting as:</p>     

			<label class="checkbox inline">
			  <input type="checkbox">T
		        </label>

			<label class="checkbox inline">
			  <input type="checkbox">S
		        </label>

			<label class="checkbox inline">
			  <input type="checkbox">Both
		        </label>

		    </form>

	    </div>

	    <div class="modal-footer">
		    <button class="btn btn-danger" data-dismiss="modal" aria-hidden="true">cancel</button>
		    <button class="btn btn-success">register</button>

	    </div>

    </div>    

    <!--script src="http://code.jquery.com/jquery.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script type="text/javascript">
	    $("#tip").tooltip();
    </script-->

  </body>
</html>

Backend/main_app/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

Backend/main_app/app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>
<% end %>

Backend/main_app/app/views/layouts/_navigation-old.html.erb
<%= link_to "Home", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
    </li>
  <% else %>
    <li>
    <%= link_to 'Login', new_user_session_path %>
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Edit account', edit_user_registration_path %>
    </li>
  <% else %>
    <li>
    <%= link_to 'Sign up', new_user_registration_path %>
    </li>
  <% end %>
  <li>
  <%= link_to 'Show Users', :users %>
  </li>
</ul>

Backend/main_app/app/views/layouts/_navigation.html.erb
    <div class="navbar navbar-inverse navbar-fixed-top" >
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <!--a class="brand" href="#">Project name</a-->
          <div class="nav-collapse collapse">
            <ul class="nav">
		    <li class="active"><a href="<%= root_path %>"><i class="icon-home icon-white"></i>WebProject<li></a></li>
              <li><a href="<%= about_path %>"><i class="icon-info-sign icon-white"></i>About</a></li>
	      <li><a href="#contact">Contact</a></li>

              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown1 <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="#">Action</a></li>
                  <li><a href="#">Another action</a></li>
                  <li><a href="#">Something else here</a></li>
                  <li class="divider"></li>
                  <li class="nav-header">Nav header</li>
                  <li><a href="#">Separated link</a></li>
                  <li><a href="#">One more separated link</a></li>
                </ul>
		</li>
		<li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown2 <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="#">Action</a></li>
                  <li><a href="#">Another action</a></li>
                  <li><a href="#">Something else here</a></li>
                  <li class="divider"></li>
                  <li class="nav-header">Nav header</li>
                  <li><a href="#">Separated link</a></li>
                  <li><a href="#">One more separated link</a></li>
                </ul>
		</li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>




Backend/main_app/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

Backend/main_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>

  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <div id="container" class="container">
      <header>
        <%= render 'layouts/navigation' %>
		<!--%= render 'layouts/messages' %-->
      </header>
      <div id="main" role="main">
        <%= yield %>
	    <%= render 'layouts/footer' %>
      </div>
    </div> <!--! end of #container -->
  </body>
</html>

Backend/main_app/app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>This is about page</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

Backend/main_app/app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.org/contact">contact page</a>.
</p>

Backend/main_app/app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

Backend/main_app/app/views/static_pages/home-orig.html.erb
<% provide(:title, 'Home') %>
   <div class="container"> 

   <div class="row" id="main-content">

   <div class="span8">
   <div id="slider" class="carousel slide">
   <div class="carousel-inner">
   <div class="item active">
     <img src="http://placehold.it/850x500">
     <div class="carousel-caption">
           <h4>Headline for Image 1</h4>
           <p>Description of image 1</p>
     </div>
   </div>
   <div class="item">
   <img src="http://placehold.it/850x500">
   <div class="carousel-caption">
   <h4>Headline for Image 2</h4>
   <p>Description of image 2</p>
   </div>
   </div>
   <div class="item">
   <img src="http://placehold.it/850x500">
   <div class="carousel-caption">
   <h4>Headline for Image 3</h4>
   <p>Description of image 3</p>
   </div>
   </div>
   </div>
   <a class="left carousel-control" href="#slider" data-slide="prev">&lsaquo;</a>
   <a class="right carousel-control" href="#slider" data-slide="prev">&rsaquo;</a>
   </div>
   </div>

   <div class="span4">
   <div class="well">
   <form>
   <fieldset>
   <legend>Login</legend>
   <input type="text" class="input-block-level" placeholder="username">
   <input type="text" class="input-block-level" placeholder="password">
   <label class="checkbox">
   <input type="checkbox">Remember me
   </label>
   <div class="pull-right">
   <input type="submit" class="btn btn-primary" value="login">

   <!--%= link_to "Register", new_user_registration_path, class:"btn btn-info", "data-toggle"=>"modal" %-->
</div>

   </fieldset>
   <p style="text-align:center">____OR____</p>
   <p>Sign in with:</p>
   <a href="#" onclick="GR_Facebook.loginAndRedirect(); return false; "><img alt="Connect your Facebook account" src="../../assets/images/button_facebook.png" title="Connect your Facebook account" /></a>
   <a href="#" onclick="GR_Twitter.askToConnect(); return false;"><img alt="Sign in with Twitter" src="../../assets/images/button_twitter.png" title="Sign in with your Twitter account" /></a>
   <a href="/user/google_sign_in"><img alt="Sign in with Google" src="../../assets/images/button_google.png" title="Sign in with your Google account" /></a>

   </form>
   </div>

   </div>

   <footer class="row"></footer>

   </div> <!end of container>
    </div>

    <div id="register" class="modal hide fade" aria-labelledby="modalLabel" aria-hidden="true">

   <div class="modal-header">
   <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="icon-remove"></i>
   <h3 id=modamlabel">Register</h3>

   </div>

   <div class="modal-body">
   <form>

   <p class="label label-info">Required</p>

   <div class="controls controls-group info">
   <input type="text" class="span4" placeholder="username" id="inputinfo">
   <input type="text" class="span4" placeholder="email" id="inputinfo">
   <input type="text" class="span4" placeholder="password" id="inputinfo">
   </div>

   <p class="help-block">I will be posting as:</p>

<label class="checkbox inline">
 <input type="checkbox">T
       </label>

<label class="checkbox inline">
 <input type="checkbox">S
       </label>

<label class="checkbox inline">
 <input type="checkbox">Both
       </label>

   </form>

   </div>

   <div class="modal-footer">
   <button class="btn btn-danger" data-dismiss="modal" aria-hidden="true">cancel</button>
   <button class="btn btn-success">register</button>

   </div>

    </div>
    <script src="http://code.jquery.com/jquery.js"></script>
    <script src="app/assets/javascripts/bootstrap.min.js"></script>
    <script type="text/javascript">
   $("#tip").tooltip();
    </script>

  </body>
</html>

Backend/main_app/app/views/static_pages/home.html.erb
<!DOCTYPE html>
<html lang="en">

    <div class="container"> 

	    <div class="row" id="main-content">

		    <div class="span8">
			    <div id="slider" class="carousel slide">
				    <div class="carousel-inner">
					    <div class="item active">
						    <img src="http://placehold.it/850x500">
						    <div class="carousel-caption">
							    <h4>Headline for Image 1</h4>
							    <p>Description of image 1</p>
						    </div>
					    </div>
					    <div class="item">
						    <img src="http://placehold.it/850x500">
						    <div class="carousel-caption">
							    <h4>Headline for Image 2</h4>
							    <p>Description of image 2</p>
						    </div>
					    </div>
					    <div class="item">
						    <img src="http://placehold.it/850x500">
						    <div class="carousel-caption">
							    <h4>Headline for Image 3</h4>
							    <p>Description of image 3</p>
						    </div>
					    </div>
				    </div>
				    <a class="left carousel-control" href="#slider" data-slide="prev">&lsaquo;</a>
				    <a class="right carousel-control" href="#slider" data-slide="prev">&rsaquo;</a>
			    </div>
		    </div>
        
		    <div class="span4"> 
				<% if user_signed_in? %>
                  <li>
                    <!--%= render 'layouts/signed_in' %-->
					Already signed in
                  </li>
                <% else %>
                  <li>
				    <%= render 'users/sign_in' %>
                  </li>
                <% end %>
			</div>

		    <footer class="row"></footer>
 
	    </div> <!end of container> 
    </div>

    <div id="register" class="modal hide fade" aria-labelledby="modalLabel" aria-hidden="true">

	    <div class="modal-header">
		    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><i class="icon-remove"></i>
			    <h3 id=modamlabel">Register</h3>

	    </div>

	    <div class="modal-body">
		    <form>

			    <p class="label label-info">Required</p>

			    <div class="controls controls-group info">
				    <input type="text" class="span4" placeholder="username" id="inputinfo">
				    <input type="text" class="span4" placeholder="email" id="inputinfo">
				    <input type="text" class="span4" placeholder="password" id="inputinfo">
			    </div>

			    <p class="help-block">I will be posting as:</p>     

			<label class="checkbox inline">
			  <input type="checkbox">T
		        </label>

			<label class="checkbox inline">
			  <input type="checkbox">S
		        </label>

			<label class="checkbox inline">
			  <input type="checkbox">Both
		        </label>

		    </form>

	    </div>

	    <div class="modal-footer">
		    <button class="btn btn-danger" data-dismiss="modal" aria-hidden="true">cancel</button>
		    <button class="btn btn-success">register</button>

	    </div>

    </div>    

    <!--script src="http://code.jquery.com/jquery.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script type="text/javascript">
	    $("#tip").tooltip();
    </script-->

  </body>
</html>


Backend/main_app/app/views/users/_sign_in.html.erb
<div class="well">
	<fieldset>
			
			<legend>Login</legend>
			<%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
			  <div><%= f.label :email %>
			  <%= f.email_field :email, :autofocus => true %>
			  <div><%= f.label :password %>
			  <%= f.password_field :password %>
			<% end %>
			<label class="checkbox">
				<input type="checkbox">Remember me
			</label>
			<div class="pull-right">
				<input type="submit" class="btn btn-primary" value="login">
				<a class="btn btn-info" href="#register" role="button" data-toggle="modal">register</a>
			</div>

		</fieldset>
		<p style="text-align:center">____OR____</p>
		<p>Sign in with:</p>
		<a href="#" onclick="GR_Facebook.loginAndRedirect(); return false; "><img alt="Connect your Facebook account" src="assets/button_facebook-3a7b74d704205be9cac5a3c59d06dee0.png" title="Connect your Facebook account" /></a>
		<a href="#" onclick="GR_Twitter.askToConnect(); return false;"><img alt="Sign in with Twitter" src="assets/button_twitter-4b3dc65449d12c332b6d817f9bb8364a.png" title="Sign in with your Twitter account" /></a>
		<a href="/user/google_sign_in"><img alt="Sign in with Google" src="assets/button_google-766f9175b047c8af47eabb022fb15f5b.png" title="Sign in with your Google account" /></a>

</div>

Backend/main_app/app/views/users/index.html.erb
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %> signed up <%= user.created_at.to_date %>
    </li>
  <% end %>
</ul>

Backend/main_app/app/views/users/show.html.erb
<h1>User Profile Page</h1>
<p>Find me in app/views/users/show.html.erb</p>
<p><b>This should be replaced with the profile page later!!</b></p>

<h3>Profile</h3>
<p><b>Name: </b><%= @user.name%></p>
<p><b>Email: </b><%= @user.email%></p>